### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by lgwapnitsky** [bhj/KaraokeEternal#24]
I'm having issues getting this app to reverse proxy under nginx or apache. Have you any advice?

Thank you

**Comment by snogrammer** [comment]
If you're willing to switch over to [Caddy](https://caddyserver.com/), it's an awesome reverse proxy that manages certs automatically and easily configurable. Below is the Docker setup that I have if you're interested:

- docker-compose.yml

```
---
version: "3.4"
services:
  caddy:
    build:
      context: .
      dockerfile: /srv/docker-compose/Dockerfile.caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - /srv/caddy/config:/config
      - /srv/caddy/data:/data
      - /srv/caddy/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - CLOUDFLARE_API_TOKEN=CHANGE_ME
      - CLOUDFLARE_EMAIL=CHANGE_ME
      - MY_DOMAIN=CHANGE_ME

  # Updates Cloudflare with your local IP to proxy
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=CHANGE_ME
      - ZONE=CHANGE_ME
      - PROXIED=false
      - RRTYPE=A

  karaoke-forever:
    image: david510c/karaoke-forever
    container_name: karaoke-forever
    volumes:
      - /mnt/data/karaoke/cdg:/cdgfiles
    ports:
      - 80:80

networks:
  default:
    external:
      name: caddy_net
```

-  /srv/docker-compose/Dockerfile.caddy

```
FROM caddy:2-builder AS builder

RUN caddy-builder \
    github.com/caddy-dns/cloudflare

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

- /srv/caddy/Caddyfile

```
your-domain.com {
  reverse_proxy karaoke-forever:80

  tls {
    dns cloudflare {env.CLOUDFLARE_API_TOKEN}
  }
}
```
